/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_link_trust_platerecognize_PlateRecognizeLib */

#ifndef _Included_com_link_trust_platerecognize_PlateRecognizeLib
#define _Included_com_link_trust_platerecognize_PlateRecognizeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    InitSVM
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_InitSVM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    InitANN
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_InitANN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    Recongize1
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_Recongize1
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    Recongize2
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_Recongize2
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    Recognize3
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_Recognize3
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_link_trust_platerecognize_PlateRecognizeLib
 * Method:    Recongize4
 * Signature: (II[BLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_1trust_platerecognize_PlateRecognizeLib_Recongize4
  (JNIEnv *, jobject, jint, jint, jbyteArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
