/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_link_trust_platerecognize_MainActivity */

#ifndef _Included_com_link_trust_platerecognize_MainActivity
#define _Included_com_link_trust_platerecognize_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_link_trust_platerecognize_MainActivity
 * Method:    recognize
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_1trust_platerecognize_MainActivity_recognize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
